In [1]:
import numpy as np
import time

In [13]:
# vectorization

a = np.random.rand(1000000)
b = np.random.rand(1000000)


tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print("Time Taken: " + str((toc-tic)*1000) + "ms")


# loop
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("Time Taken: " + str((toc-tic)*1000) + "ms")

249738.58094214785
Time Taken: 0.9119510650634766ms
249738.5809421513
Time Taken: 392.9929733276367ms


In [14]:
# Broadcasting

A = np.array([[56,0,4.4,68],
             [1.2, 104, 52, 8],
             [1.8, 135, 99, 0.9]])

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [16]:
cal = np.sum(A, axis=0)
cal

array([ 59. , 239. , 155.4,  76.9])

In [20]:
perc = A*100/cal.reshape(1,4)
perc

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])